### PR TITLE
Import SNOMED CT to MS SQL DB

### PR DESCRIPTION
**Pull request by SelAnt**
Hi,

I created script(s) to create MS SQL DB and import SNOMED CT Full content to it

### CODE REVIEW

**Comment by pgwilliams** [comment]
Hey, that's a really useful contribution.  Thank you so much SelAnt!
    
I found the commits a little confusing though.  I think you coded this by making changes to the Postgres version, then copying that into a new MS SQL directory and putting the Postgres back the way it was?   Would it be OK for us just to cherry pick 215cd24 from your repo, so that we just obtain the new code?    Or if you'd prefer to create a new pull request with just that one commit?

Thanks & Best Wishes,
Peter

**Comment by siamchen** [comment]
Should we standardise the database table names between different database server? Currently, MySQL and PostgreSQL tables names are different. The tables in PostgreSQL server have a prefix of "curr_". I believe that need to be removed and make all the tables same as MySQL server. In that case, this MS SQL server version also needs to remove the prefix from the tables.

**Comment by pgwilliams** [comment]
Yes, agree.  I'm not a fan of curr_  (meaning current) and prev_ (previous) prefixes because a) it's extra characters to type and b) what we consider to be "current" changes every 6 months.   I've taken to naming the schema/database with the release date so a specific table can be reference eg int_20170131.concept_s  Then you know exactly which edition you're referencing and it doesn't change when a new edition comes out.

**Comment by SelAnt** [comment]
Hi,

No problem, pleas pick just  215cd24
<https://github.com/IHTSDO/snomed-database-loader/commit/215cd24218db002348803255d2f5da97883763a0>
from
my repo.

Thank you,
Gleb

2017-08-17 5:04 GMT-04:00 Peter G. Williams <notifications@github.com>:

**Comment by pgwilliams** [comment]
Hi @SelAnt  Great work, much appreciated thank you!   Finally got around to a clean up, and pinched that commit directly from your repo so I can close this pull request.   Best Wishes @pgwilliams

**Pull request closed without merging**
